// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: spot_instrument_v1/spot_intrument_service_messages.proto

package spot_instrument_v1

import (
	pkg "github.com/ewik2k21/grpcSpotInstrumentService/pkg"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRole      pkg.UserRole           `protobuf:"varint,1,opt,name=user_role,json=userRole,proto3,enum=common.UserRole" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsRequest) Reset() {
	*x = ViewMarketsRequest{}
	mi := &file_spot_instrument_v1_spot_intrument_service_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsRequest) ProtoMessage() {}

func (x *ViewMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_v1_spot_intrument_service_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsRequest) Descriptor() ([]byte, []int) {
	return file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ViewMarketsRequest) GetUserRole() pkg.UserRole {
	if x != nil {
		return x.UserRole
	}
	return pkg.UserRole(0)
}

type ViewMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*Market              `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsResponse) Reset() {
	*x = ViewMarketsResponse{}
	mi := &file_spot_instrument_v1_spot_intrument_service_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsResponse) ProtoMessage() {}

func (x *ViewMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_v1_spot_intrument_service_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsResponse) Descriptor() ([]byte, []int) {
	return file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarketsResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

type Market struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_spot_instrument_v1_spot_intrument_service_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_spot_instrument_v1_spot_intrument_service_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Market) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Market) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_spot_instrument_v1_spot_intrument_service_messages_proto protoreflect.FileDescriptor

const file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDesc = "" +
	"\n" +
	"8spot_instrument_v1/spot_intrument_service_messages.proto\x12\x12spot_instrument_v1\x1a\fcommon.proto\"C\n" +
	"\x12ViewMarketsRequest\x12-\n" +
	"\tuser_role\x18\x01 \x01(\x0e2\x10.common.UserRoleR\buserRole\"K\n" +
	"\x13ViewMarketsResponse\x124\n" +
	"\amarkets\x18\x01 \x03(\v2\x1a.spot_instrument_v1.MarketR\amarkets\",\n" +
	"\x06Market\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameBFZDgithub.com/ewik2k21/grpcSpotInstrumentService/pkg/spot_instrument_v1b\x06proto3"

var (
	file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDescOnce sync.Once
	file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDescData []byte
)

func file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDescGZIP() []byte {
	file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDescOnce.Do(func() {
		file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDesc), len(file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDesc)))
	})
	return file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDescData
}

var file_spot_instrument_v1_spot_intrument_service_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spot_instrument_v1_spot_intrument_service_messages_proto_goTypes = []any{
	(*ViewMarketsRequest)(nil),  // 0: spot_instrument_v1.ViewMarketsRequest
	(*ViewMarketsResponse)(nil), // 1: spot_instrument_v1.ViewMarketsResponse
	(*Market)(nil),              // 2: spot_instrument_v1.Market
	(pkg.UserRole)(0),           // 3: common.UserRole
}
var file_spot_instrument_v1_spot_intrument_service_messages_proto_depIdxs = []int32{
	3, // 0: spot_instrument_v1.ViewMarketsRequest.user_role:type_name -> common.UserRole
	2, // 1: spot_instrument_v1.ViewMarketsResponse.markets:type_name -> spot_instrument_v1.Market
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spot_instrument_v1_spot_intrument_service_messages_proto_init() }
func file_spot_instrument_v1_spot_intrument_service_messages_proto_init() {
	if File_spot_instrument_v1_spot_intrument_service_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDesc), len(file_spot_instrument_v1_spot_intrument_service_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spot_instrument_v1_spot_intrument_service_messages_proto_goTypes,
		DependencyIndexes: file_spot_instrument_v1_spot_intrument_service_messages_proto_depIdxs,
		MessageInfos:      file_spot_instrument_v1_spot_intrument_service_messages_proto_msgTypes,
	}.Build()
	File_spot_instrument_v1_spot_intrument_service_messages_proto = out.File
	file_spot_instrument_v1_spot_intrument_service_messages_proto_goTypes = nil
	file_spot_instrument_v1_spot_intrument_service_messages_proto_depIdxs = nil
}
